[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
gas_reports=["*"]
optimizer = true
via_ir = false
optimizer-runs = 20_000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
#base_chain = { key="${ETHERSCAN_API_KEY}", chain=8453, url = "https://api.basescan.org/api" }
